credentials:
  usernames:
    jsmith:
      email: user@demo.com
      name: John Smith
      password: Pa$$w0rd
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: def 
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
    - email: user@demo.com