credentials:
  usernames:
    demo@gmail.com:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$LFaXwPDbJqX6/hinE9xGFOrJcldmSSvAolJrDQpVsv.KuvEywfpEu
    user@gmail.com:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: Pa$$w0rd
cookie:
  expiry_days: 0
  key: abcdef 
  name: solar_panel
preauthorized:
  emails:
  - melsby@gmail.com